version: '2.0'

volumes:
  opt-splunk-etc:
  opt-splunk-var:

services:
  splunkenterprise:
    image: splunk/splunk:7.0.3
    container_name: server
    hostname: splunkenterprise-docker
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_DEPLOY_SERVER: 'true'
      SPLUNK_ENABLE_LISTEN: 9997
    volumes:
      - /data/splunk/opt-splunk-etc:/opt/splunk/etc
      - /data/splunk/opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"


